### ISSUE TITLE
Cannot find ng-bokeh Module

### ISSUE THREAD

**Issue by StewSchrieff** [Shekharrajak/ng-bokeh#2]
> ERROR in projects/bokeh-tester/src/app/app.module.ts(5,31): error TS2307: Cannot find module 'ng-bokeh'.

After running `npm i`, I'm unable to `ng serve` the project due to not being able to find the ng-bokeh module. I've seen similar issues online be resolved by using relative pathing, but I've been unable to change app.module.ts to work. 

Am I missing any steps in order to run this project?

Thanks for your time.

**Comment by StewSchrieff** [comment]
I'm also unable to`ng build ng-bokeh`...

> BUILD ERROR
> ng-bokeh/src/lib/ng-bokeh.component.ts(16,17): error TS2552: Cannot find name 'plt2'. Did you mean 'plt'?
> 
> Error: ng-bokeh/src/lib/ng-bokeh.component.ts(16,17): error TS2552: Cannot find name 'plt2'. Did you mean 'plt'?
> 
>     at Object.<anonymous> (C:\Users\Stewart\WebstormProjects\bokeh-example\ng-bokeh\node_modules\ng-packagr\lib\ngc\compile-source-files.js:51:19)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\Stewart\WebstormProjects\bokeh-example\ng-bokeh\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
>     at <anonymous>
>

**Comment by Shekharrajak** [comment]
Thanks for letting me know this issue. I will verify it and let you know.

**Comment by Shekharrajak** [comment]
I believe, you should have error like this : https://github.com/Shekharrajak/ng-bokeh/issues/1
